import {
  DeviceSettings,
  Meeting,
  MeetingParticipant,
} from './types';

export const CURRENT_USER: MeetingParticipant = {
  id: 'user-self',
  name: 'Alex Morgan (You)',
  email: 'alex.morgan@codin.io',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
  role: 'host',
  responseStatus: 'accepted',
  isMuted: false,
  isVideoOn: true,
  isSpeaking: false,
  audioLevel: 0,
  connectionQuality: 'good',
};

export const MOCK_PARTICIPANTS_POOL: MeetingParticipant[] = [
  CURRENT_USER,
  {
    id: 'user-maya',
    name: 'Maya Chen',
    email: 'maya.chen@codin.io',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
    role: 'participant',
    responseStatus: 'accepted',
    isMuted: false,
    isVideoOn: true,
    isSpeaking: true,
    audioLevel: 75,
    connectionQuality: 'good',
  },
  {
    id: 'user-lee',
    name: 'Lee Robinson',
    email: 'lee@codin.io',
    avatar: 'https://github.com/leerob.png',
    role: 'participant',
    responseStatus: 'accepted',
    isMuted: false,
    isVideoOn: true,
    isSpeaking: false,
    audioLevel: 0,
    connectionQuality: 'good',
  },
  {
    id: 'user-guillermo',
    name: 'Guillermo Rauch',
    email: 'rauchg@codin.io',
    avatar: 'https://github.com/rauchg.png',
    role: 'participant',
    responseStatus: 'accepted',
    isMuted: true,
    isVideoOn: true,
    isSpeaking: false,
    audioLevel: 0,
    connectionQuality: 'good',
  },
  {
    id: 'user-delba',
    name: 'Delba de Oliveira',
    email: 'delba.oliveira@codin.io',
    avatar: 'https://github.com/delbaoliveira.png',
    role: 'participant',
    responseStatus: 'accepted',
    isMuted: false,
    isVideoOn: true,
    isSpeaking: false,
    audioLevel: 10,
    connectionQuality: 'good',
  },
  {
    id: 'user-tim',
    name: 'Tim Neutkens',
    email: 'tim@codin.io',
    avatar: 'https://github.com/timneutkens.png',
    role: 'participant',
    responseStatus: 'accepted',
    isMuted: true,
    isVideoOn: false,
    isSpeaking: false,
    audioLevel: 0,
    connectionQuality: 'good',
  },
  {
    id: 'user-sarah',
    name: 'Sarah Jenkins',
    email: 'sarah.j@acmecorp.com',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80',
    role: 'guest',
    responseStatus: 'accepted',
    isMuted: false,
    isVideoOn: true,
    isSpeaking: false,
    audioLevel: 0,
    connectionQuality: 'fair',
  },
];

export const DEFAULT_DEVICE_SETTINGS: DeviceSettings = {
  microphoneId: 'default-mic-1',
  cameraId: 'default-cam-1',
  speakerId: 'default-speaker-1',
  isMicMuted: false,
  isVideoOff: false,
  isNoiseSuppressionEnabled: true,
  isVirtualBackgroundEnabled: false,
  virtualBackgroundStyle: 'blur',
  mirrorCamera: true,
};

export function generateInitialMeetings(): Meeting[] {
  return [
    {
      id: 'meet-ops-weekly',
      title: 'Weekly Operations & Architecture Sync',
      description: 'Reviewing quarterly cloud infrastructure margins, active tenant capacity, and V2 design milestones.',
      organizerId: 'user-self',
      organizerName: 'Alex Morgan',
      organizerEmail: 'alex.morgan@codin.io',
      provider: 'google_meet',
      providerMeetingId: 'gmeet-9912',
      meetingCode: 'ops-arch-sync',
      meetingUrl: 'https://meet.google.com/ops-arch-sync',
      scheduledStart: '2026-08-24T10:00:00',
      scheduledEnd: '2026-08-24T11:00:00',
      actualStartTime: '2026-08-24T10:02:00',
      timezone: 'America/New_York (EDT)',
      status: 'in_progress',
      participants: [
        MOCK_PARTICIPANTS_POOL[0],
        MOCK_PARTICIPANTS_POOL[1],
        MOCK_PARTICIPANTS_POOL[2],
        MOCK_PARTICIPANTS_POOL[3],
        MOCK_PARTICIPANTS_POOL[4],
      ],
      messages: [
        {
          id: 'msg-1',
          meetingId: 'meet-ops-weekly',
          senderId: 'user-maya',
          senderName: 'Maya Chen',
          senderAvatar: MOCK_PARTICIPANTS_POOL[1].avatar,
          content: 'I have uploaded the new design tokens and grid specifications to the files tab.',
          timestamp: '10:05 AM',
        },
        {
          id: 'msg-2',
          meetingId: 'meet-ops-weekly',
          senderId: 'user-lee',
          senderName: 'Lee Robinson',
          senderAvatar: MOCK_PARTICIPANTS_POOL[2].avatar,
          content: 'Turbopack build times dropped by 45% in canary 59. Super solid release.',
          timestamp: '10:08 AM',
        },
        {
          id: 'msg-3',
          meetingId: 'meet-ops-weekly',
          senderId: 'user-self',
          senderName: 'Alex Morgan',
          senderAvatar: MOCK_PARTICIPANTS_POOL[0].avatar,
          content: 'Great. Lets confirm the SOC2 European residency requirements with Sarah this afternoon.',
          timestamp: '10:11 AM',
        },
      ],
      files: [
        {
          id: 'file-1',
          meetingId: 'meet-ops-weekly',
          name: 'Q3_Operations_Deck_v4.pdf',
          size: '3.8 MB',
          type: 'PDF',
          uploadedBy: 'Maya Chen',
          uploadedAt: '10:04 AM',
        },
        {
          id: 'file-2',
          meetingId: 'meet-ops-weekly',
          name: 'Infrastructure_Capacity_Model.xlsx',
          size: '1.2 MB',
          type: 'Excel',
          uploadedBy: 'Alex Morgan',
          uploadedAt: '10:01 AM',
        },
      ],
      tasks: [
        {
          id: 'task-1',
          meetingId: 'meet-ops-weekly',
          title: 'Finalize AWS multi-region discount commit',
          completed: false,
          assigneeName: 'Alex Morgan',
          dueDate: '2026-08-28',
          priority: 'high',
        },
        {
          id: 'task-2',
          meetingId: 'meet-ops-weekly',
          title: 'Review high-contrast dark mode palette in Figma',
          completed: true,
          assigneeName: 'Maya Chen',
          dueDate: '2026-08-25',
          priority: 'medium',
        },
      ],
      notes: {
        id: 'notes-1',
        meetingId: 'meet-ops-weekly',
        agendaItems: [
          '1. Revenue & Pipeline Review for August',
          '2. Architecture Scaling & Google Meet Provider Adapter',
          '3. Q&A and Action Items Assignment',
        ],
        notesContent:
          '• Infrastructure margins improved by +8% month-over-month.\n• Confirmed provider abstraction isolates Google Meet embed SDK from UI layer.\n• Action items logged directly to Codin Tasks.',
        decisions: [
          'Approved provider-agnostic meeting architecture for enterprise roll-out.',
          'Scheduled Customer Advisory Board session for Thursday.',
        ],
        updatedAt: '10:14 AM',
      },
      aiSummary: {
        summary:
          'The team aligned on the new unified communication suite architecture. Key priorities include finalizing infrastructure capacity discounts, testing the Google Meet provider adapter, and completing mobile responsive layouts.',
        keyDecisions: [
          'Adopt provider abstraction layer to support Google Meet and future conferencing backends.',
          'Retain native Codin side panels for notes, tasks, chat, and AI during live calls.',
        ],
        extractedActionItems: [
          {
            title: 'Prepare European cluster latency benchmarks',
            assignee: 'Lee Robinson',
            dueDate: '2026-08-25',
          },
          {
            title: 'Draft follow-up email with revised architecture diagram',
            assignee: 'Alex Morgan',
            dueDate: '2026-08-24',
          },
        ],
        followUpEmailDraft: {
          subject: 'Action Items & Summary: Weekly Operations & Architecture Sync',
          recipients: ['maya.chen@codin.io', 'lee@codin.io', 'rauchg@codin.io'],
          body:
            'Hi team,\n\nThanks for joining today’s sync. Here is a brief recap:\n\n1. Key Decisions: We approved the provider-agnostic meeting architecture to support Google Meet seamlessly.\n2. Action Items: Lee to finalize latency benchmarks; Maya to review high-contrast accessibility.\n\nBest,\nAlex Morgan',
        },
        sentiment: 'productive',
        topicsDiscussed: ['Architecture Scaling', 'Provider Abstraction', 'Infrastructure Margins'],
      },
      createdAt: '2026-08-20T08:00:00Z',
      updatedAt: '2026-08-24T10:15:00Z',
    },
    {
      id: 'meet-design-crit',
      title: 'Design Critique: Unified Suite & Video Canvas',
      description: 'Reviewing active speaker transitions, video grid responsive breakpoints, and toolbar micro-interactions.',
      organizerId: 'user-maya',
      organizerName: 'Maya Chen',
      organizerEmail: 'maya.chen@codin.io',
      provider: 'google_meet',
      providerMeetingId: 'gmeet-4421',
      meetingCode: 'des-crit-332',
      meetingUrl: 'https://meet.google.com/des-crit-332',
      scheduledStart: '2026-08-24T14:00:00',
      scheduledEnd: '2026-08-24T15:00:00',
      timezone: 'America/New_York (EDT)',
      status: 'upcoming',
      participants: [
        MOCK_PARTICIPANTS_POOL[1],
        MOCK_PARTICIPANTS_POOL[0],
        MOCK_PARTICIPANTS_POOL[4],
        MOCK_PARTICIPANTS_POOL[5],
      ],
      messages: [],
      files: [
        {
          id: 'file-3',
          meetingId: 'meet-design-crit',
          name: 'Meet_Design_System_Spec.pdf',
          size: '5.2 MB',
          type: 'PDF',
          uploadedBy: 'Maya Chen',
          uploadedAt: 'Yesterday',
        },
      ],
      tasks: [
        {
          id: 'task-3',
          meetingId: 'meet-design-crit',
          title: 'Verify screen reader announcements for speaker change',
          completed: false,
          assigneeName: 'Delba de Oliveira',
          dueDate: '2026-08-24',
          priority: 'high',
        },
      ],
      createdAt: '2026-08-21T09:00:00Z',
      updatedAt: '2026-08-24T09:00:00Z',
    },
    {
      id: 'meet-acme-procurement',
      title: 'Enterprise Architecture & Procurement (Acme Corp)',
      description: 'Technical evaluation call with Acme Corp security leads regarding SSO, data residency, and audit logs.',
      organizerId: 'user-self',
      organizerName: 'Alex Morgan',
      organizerEmail: 'alex.morgan@codin.io',
      provider: 'google_meet',
      providerMeetingId: 'gmeet-8831',
      meetingCode: 'acme-procure-call',
      meetingUrl: 'https://meet.google.com/acme-procure-call',
      scheduledStart: '2026-08-25T15:30:00',
      scheduledEnd: '2026-08-25T16:30:00',
      timezone: 'America/New_York (EDT)',
      status: 'scheduled',
      participants: [
        MOCK_PARTICIPANTS_POOL[0],
        MOCK_PARTICIPANTS_POOL[6],
        MOCK_PARTICIPANTS_POOL[3],
      ],
      messages: [],
      files: [
        {
          id: 'file-4',
          meetingId: 'meet-acme-procurement',
          name: 'SOC2_Type_II_Executive_Summary.pdf',
          size: '1.9 MB',
          type: 'PDF',
          uploadedBy: 'Alex Morgan',
          uploadedAt: 'Aug 22',
        },
      ],
      tasks: [],
      createdAt: '2026-08-22T14:00:00Z',
      updatedAt: '2026-08-24T09:30:00Z',
    },
    {
      id: 'meet-past-roadmap',
      title: 'Q4 Product Roadmap & Executive Review',
      description: 'Strategic roadmap review with Guillermo and product leadership regarding AI workflows and enterprise readiness.',
      organizerId: 'user-guillermo',
      organizerName: 'Guillermo Rauch',
      organizerEmail: 'rauchg@codin.io',
      provider: 'google_meet',
      providerMeetingId: 'gmeet-1029',
      meetingCode: 'q4-road-exec',
      meetingUrl: 'https://meet.google.com/q4-road-exec',
      scheduledStart: '2026-08-21T11:00:00',
      scheduledEnd: '2026-08-21T12:00:00',
      actualStartTime: '2026-08-21T11:00:00',
      actualEndTime: '2026-08-21T11:52:00',
      durationMinutes: 52,
      timezone: 'America/New_York (EDT)',
      status: 'ended',
      participants: [
        MOCK_PARTICIPANTS_POOL[3],
        MOCK_PARTICIPANTS_POOL[0],
        MOCK_PARTICIPANTS_POOL[1],
        MOCK_PARTICIPANTS_POOL[2],
      ],
      messages: [
        {
          id: 'msg-p1',
          meetingId: 'meet-past-roadmap',
          senderId: 'user-guillermo',
          senderName: 'Guillermo Rauch',
          content: 'Let’s make sure Codin Meet feels 100% native while leveraging Google infrastructure under the hood.',
          timestamp: '11:15 AM',
        },
      ],
      files: [
        {
          id: 'file-p1',
          meetingId: 'meet-past-roadmap',
          name: 'Q4_Strategy_Blueprint.pdf',
          size: '4.1 MB',
          type: 'PDF',
          uploadedBy: 'Guillermo Rauch',
          uploadedAt: 'Aug 21',
        },
      ],
      tasks: [
        {
          id: 'task-p1',
          meetingId: 'meet-past-roadmap',
          title: 'Ship Meet and Calendar unified workspace integration',
          completed: true,
          assigneeName: 'Alex Morgan',
          dueDate: '2026-08-24',
          priority: 'high',
        },
      ],
      notes: {
        id: 'note-p1',
        meetingId: 'meet-past-roadmap',
        agendaItems: ['1. Roadmap Prioritization', '2. Enterprise Integrations', '3. Next Steps'],
        notesContent: 'All squads agreed on shipping unified communication modules (Mail, Chat, Calendar, Meet, Contacts, Tasks, Files, AI).',
        decisions: ['Prioritize Meet deep links in Calendar and Mail.'],
        updatedAt: 'Aug 21, 11:50 AM',
      },
      aiSummary: {
        summary:
          'Executive review confirming the product roadmap for Codin Meet and unified workspace modules. Guillermo highlighted the importance of clean UI ownership with Google Meet provider backing.',
        keyDecisions: [
          'Maintain Codin design language across all conferencing surfaces.',
          'Enable instant action items and task creation during meetings.',
        ],
        extractedActionItems: [
          {
            title: 'Ship Google Meet provider abstraction layer',
            assignee: 'Lee Robinson',
            dueDate: '2026-08-24',
          },
        ],
        sentiment: 'collaborative',
        topicsDiscussed: ['Unified Platform', 'Video Conferencing', 'Product Roadmap'],
      },
      recording: {
        id: 'rec-102',
        meetingId: 'meet-past-roadmap',
        durationMinutes: 52,
        recordedAt: 'Aug 21, 2026',
        size: '142 MB',
        status: 'ready',
      },
      createdAt: '2026-08-18T10:00:00Z',
      updatedAt: '2026-08-21T12:00:00Z',
    },
  ];
}
