import { Task, TaskLabel } from './types';

const today = '2026-08-25';
const yesterday = '2026-08-24';
const twoDaysAgo = '2026-08-23';
const lastWeek = '2026-08-18';
const tomorrow = '2026-08-26';
const nextWeek = '2026-09-01';
const nextMonth = '2026-09-15';

export const mockLabels: TaskLabel[] = [
  { id: 'label-sales', name: 'Sales', color: '#c92b2b' },
  { id: 'label-follow-up', name: 'Follow-up', color: '#176b87' },
  { id: 'label-finance', name: 'Finance', color: '#96711f' },
  { id: 'label-operations', name: 'Operations', color: '#34745b' },
  { id: 'label-urgent', name: 'Urgent', color: '#b42318' },
  { id: 'label-personal', name: 'Personal', color: '#637180' },
  { id: 'label-fleet', name: 'Fleet', color: '#4e8372' },
  { id: 'label-proposal', name: 'Proposal', color: '#92400e' },
  { id: 'label-legal', name: 'Legal', color: '#475569' },
];

export const mockTasks: Task[] = [
  {
    id: 'task-001',
    organizationId: 'org-codin',
    creatorId: 'user-kelvin',
    assigneeId: 'user-kelvin',
    title: 'Follow up with ABC Ltd regarding fleet proposal',
    description: 'ABC Ltd requested a revised fleet proposal for 15 vehicles. Need to follow up on their feedback and confirm pricing before end of month.',
    status: 'in_progress',
    priority: 'high',
    dueDate: today,
    dueTime: '14:00',
    reminder: '30_min',
    recurrence: 'none',
    labels: [mockLabels[0], mockLabels[7], mockLabels[6]],
    subtasks: [
      { id: 'sub-001a', title: 'Review revised pricing sheet', completed: true, createdAt: lastWeek },
      { id: 'sub-001b', title: 'Confirm vehicle availability with supplier', completed: true, createdAt: lastWeek },
      { id: 'sub-001c', title: 'Draft response email to procurement', completed: false, createdAt: twoDaysAgo },
    ],
    attachments: [
      { id: 'att-001', name: 'ABC-Ltd-Fleet-Proposal-v2.pdf', size: 2400000, type: 'application/pdf', url: '#' },
    ],
    comments: [
      { id: 'com-001', authorId: 'user-john', authorName: 'John Smith', text: 'They mentioned budget approval is pending. Might need to extend the quote validity.', createdAt: yesterday },
    ],
    activity: [
      { id: 'act-001a', action: 'created task', userId: 'user-kelvin', userName: 'Kelvin Kijazi', createdAt: lastWeek },
      { id: 'act-001b', action: 'changed status to In Progress', userId: 'user-kelvin', userName: 'Kelvin Kijazi', createdAt: twoDaysAgo },
    ],
    relatedItems: [
      { type: 'email', id: 'email-001', title: 'RE: Fleet Proposal - ABC Ltd', href: '/f/inbox' },
      { type: 'contact', id: 'contact-001', title: 'James Mwangi - ABC Ltd', href: '#' },
    ],
    createdAt: lastWeek,
    updatedAt: twoDaysAgo,
    completedAt: null,
  },
  {
    id: 'task-002',
    organizationId: 'org-codin',
    creatorId: 'user-mary',
    assigneeId: 'user-mary',
    title: 'Prepare Q3 financial report',
    description: 'Compile quarterly financial statements including revenue breakdown, expense analysis, and cash flow projections for board review.',
    status: 'todo',
    priority: 'high',
    dueDate: nextWeek,
    dueTime: '09:00',
    reminder: '1_day',
    recurrence: 'none',
    labels: [mockLabels[2]],
    subtasks: [
      { id: 'sub-002a', title: 'Gather revenue data from Salesforce', completed: false, createdAt: yesterday },
      { id: 'sub-002b', title: 'Reconcile expense accounts', completed: false, createdAt: yesterday },
      { id: 'sub-002c', title: 'Draft executive summary', completed: false, createdAt: yesterday },
      { id: 'sub-002d', title: 'Review with CFO', completed: false, createdAt: yesterday },
    ],
    attachments: [],
    comments: [],
    activity: [
      { id: 'act-002a', action: 'created task', userId: 'user-mary', userName: 'Mary Chen', createdAt: yesterday },
    ],
    relatedItems: [],
    createdAt: yesterday,
    updatedAt: yesterday,
    completedAt: null,
  },
  {
    id: 'task-003',
    organizationId: 'org-codin',
    creatorId: 'user-george',
    assigneeId: 'user-george',
    title: 'Review contract with FleetCo Solutions',
    description: 'Legal review of the service agreement with FleetCo Solutions. Focus on liability clauses, termination terms, and SLA commitments.',
    status: 'waiting',
    priority: 'medium',
    dueDate: nextMonth,
    dueTime: null,
    reminder: 'none',
    recurrence: 'none',
    labels: [mockLabels[8], mockLabels[6]],
    subtasks: [
      { id: 'sub-003a', title: 'Review liability section', completed: true, createdAt: lastWeek },
      { id: 'sub-003b', title: 'Flag concerns for legal team', completed: false, createdAt: lastWeek },
    ],
    attachments: [
      { id: 'att-003', name: 'FleetCo-Service-Agreement.pdf', size: 1800000, type: 'application/pdf', url: '#' },
    ],
    comments: [
      { id: 'com-003', authorId: 'user-kelvin', authorName: 'Kelvin Kijazi', text: 'Waiting for FleetCo to confirm their insurance coverage details before proceeding.', createdAt: twoDaysAgo },
    ],
    activity: [
      { id: 'act-003a', action: 'created task', userId: 'user-george', userName: 'George Wilson', createdAt: lastWeek },
      { id: 'act-003b', action: 'changed status to Waiting', userId: 'user-george', userName: 'George Wilson', createdAt: twoDaysAgo },
    ],
    relatedItems: [],
    createdAt: lastWeek,
    updatedAt: twoDaysAgo,
    completedAt: null,
  },
  {
    id: 'task-004',
    organizationId: 'org-codin',
    creatorId: 'user-kelvin',
    assigneeId: 'user-john',
    title: 'Schedule technical meeting for proposal review',
    description: 'Coordinate with engineering and sales teams to schedule a technical review meeting for the upcoming enterprise proposal.',
    status: 'todo',
    priority: 'medium',
    dueDate: tomorrow,
    dueTime: '10:00',
    reminder: '1_hour',
    recurrence: 'none',
    labels: [mockLabels[0], mockLabels[3]],
    subtasks: [
      { id: 'sub-004a', title: 'Check team availability', completed: true, createdAt: yesterday },
      { id: 'sub-004b', title: 'Book conference room', completed: false, createdAt: yesterday },
      { id: 'sub-004c', title: 'Send calendar invites', completed: false, createdAt: yesterday },
    ],
    attachments: [],
    comments: [],
    activity: [
      { id: 'act-004a', action: 'created task', userId: 'user-kelvin', userName: 'Kelvin Kijazi', createdAt: yesterday },
    ],
    relatedItems: [
      { type: 'calendar_event', id: 'event-001', title: 'Technical Review - Enterprise Proposal', href: '#' },
    ],
    createdAt: yesterday,
    updatedAt: yesterday,
    completedAt: null,
  },
  {
    id: 'task-005',
    organizationId: 'org-codin',
    creatorId: 'user-john',
    assigneeId: 'user-john',
    title: 'Submit tender documents',
    description: 'Final submission of tender documents for the government fleet management RFP. All documents must be uploaded before 5 PM deadline.',
    status: 'in_progress',
    priority: 'urgent',
    dueDate: today,
    dueTime: '17:00',
    reminder: '1_hour',
    recurrence: 'none',
    labels: [mockLabels[4], mockLabels[3]],
    subtasks: [
      { id: 'sub-005a', title: 'Complete technical proposal', completed: true, createdAt: lastWeek },
      { id: 'sub-005b', title: 'Prepare financial bid', completed: true, createdAt: lastWeek },
      { id: 'sub-005c', title: 'Obtain company certificates', completed: true, createdAt: twoDaysAgo },
      { id: 'sub-005d', title: 'Upload to procurement portal', completed: false, createdAt: yesterday },
      { id: 'sub-005e', title: 'Confirm submission receipt', completed: false, createdAt: yesterday },
    ],
    attachments: [
      { id: 'att-005a', name: 'Technical-Proposal-Final.pdf', size: 5200000, type: 'application/pdf', url: '#' },
      { id: 'att-005b', name: 'Financial-Bid.xlsx', size: 890000, type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', url: '#' },
    ],
    comments: [
      { id: 'com-005', authorId: 'user-kelvin', authorName: 'Kelvin Kijazi', text: 'Make sure the tax certificate is the latest version from Finance.', createdAt: yesterday },
    ],
    activity: [
      { id: 'act-005a', action: 'created task', userId: 'user-john', userName: 'John Smith', createdAt: lastWeek },
      { id: 'act-005b', action: 'changed priority to Urgent', userId: 'user-john', userName: 'John Smith', createdAt: twoDaysAgo },
    ],
    relatedItems: [
      { type: 'email', id: 'email-005', title: 'RFP Notice - Government Fleet Management', href: '/f/inbox' },
    ],
    createdAt: lastWeek,
    updatedAt: yesterday,
    completedAt: null,
  },
  {
    id: 'task-006',
    organizationId: 'org-codin',
    creatorId: 'user-george',
    assigneeId: 'user-george',
    title: 'Prepare monthly fleet maintenance report',
    description: 'Compile maintenance records, costs, and vehicle downtime metrics for the monthly fleet report.',
    status: 'backlog',
    priority: 'low',
    dueDate: nextMonth,
    dueTime: null,
    reminder: 'none',
    recurrence: 'monthly',
    labels: [mockLabels[6], mockLabels[3]],
    subtasks: [],
    attachments: [],
    comments: [],
    activity: [
      { id: 'act-006a', action: 'created task', userId: 'user-george', userName: 'George Wilson', createdAt: lastWeek },
    ],
    relatedItems: [],
    createdAt: lastWeek,
    updatedAt: lastWeek,
    completedAt: null,
  },
  {
    id: 'task-007',
    organizationId: 'org-codin',
    creatorId: 'user-mary',
    assigneeId: 'user-mary',
    title: 'Send invoice to FleetCo',
    description: 'Generate and send the monthly invoice for fleet management services rendered to FleetCo Solutions.',
    status: 'todo',
    priority: 'medium',
    dueDate: tomorrow,
    dueTime: '12:00',
    reminder: 'none',
    recurrence: 'monthly',
    labels: [mockLabels[2], mockLabels[6]],
    subtasks: [
      { id: 'sub-007a', title: 'Verify service hours logged', completed: false, createdAt: yesterday },
      { id: 'sub-007b', title: 'Generate invoice from billing system', completed: false, createdAt: yesterday },
      { id: 'sub-007c', title: 'Email to accounts payable', completed: false, createdAt: yesterday },
    ],
    attachments: [],
    comments: [],
    activity: [
      { id: 'act-007a', action: 'created task', userId: 'user-mary', userName: 'Mary Chen', createdAt: yesterday },
    ],
    relatedItems: [],
    createdAt: yesterday,
    updatedAt: yesterday,
    completedAt: null,
  },
  {
    id: 'task-008',
    organizationId: 'org-codin',
    creatorId: 'user-kelvin',
    assigneeId: 'user-kelvin',
    title: 'Follow up on overdue payment',
    description: 'Contact XYZ Corp regarding invoice #INV-2026-0842 which is now 30 days overdue. Amount: $12,500.',
    status: 'in_progress',
    priority: 'high',
    dueDate: yesterday,
    dueTime: null,
    reminder: 'none',
    recurrence: 'none',
    labels: [mockLabels[1], mockLabels[2], mockLabels[4]],
    subtasks: [
      { id: 'sub-008a', title: 'Call accounts payable', completed: true, createdAt: twoDaysAgo },
      { id: 'sub-008b', title: 'Send reminder email', completed: true, createdAt: yesterday },
      { id: 'sub-008c', title: 'Escalate if no response by EOD', completed: false, createdAt: yesterday },
    ],
    attachments: [
      { id: 'att-008', name: 'INV-2026-0842.pdf', size: 450000, type: 'application/pdf', url: '#' },
    ],
    comments: [
      { id: 'com-008', authorId: 'user-mary', authorName: 'Mary Chen', text: 'They promised payment by Friday. If not received, we may need to pause services.', createdAt: today },
    ],
    activity: [
      { id: 'act-008a', action: 'created task', userId: 'user-kelvin', userName: 'Kelvin Kijazi', createdAt: twoDaysAgo },
      { id: 'act-008b', action: 'added comment', userId: 'user-mary', userName: 'Mary Chen', createdAt: today },
    ],
    relatedItems: [
      { type: 'email', id: 'email-008', title: 'Overdue Invoice Notice - XYZ Corp', href: '/f/sent' },
    ],
    createdAt: twoDaysAgo,
    updatedAt: today,
    completedAt: null,
  },
  {
    id: 'task-009',
    organizationId: 'org-codin',
    creatorId: 'user-john',
    assigneeId: 'user-john',
    title: 'Update CRM with client notes',
    description: 'Log all client interactions from this week into Salesforce. Update opportunity stages and next steps.',
    status: 'completed',
    priority: 'low',
    dueDate: yesterday,
    dueTime: null,
    reminder: 'none',
    recurrence: 'weekly',
    labels: [mockLabels[0], mockLabels[1]],
    subtasks: [
      { id: 'sub-009a', title: 'Log ABC Ltd meeting notes', completed: true, createdAt: twoDaysAgo },
      { id: 'sub-009b', title: 'Update opportunity amounts', completed: true, createdAt: twoDaysAgo },
      { id: 'sub-009c', title: 'Set follow-up reminders', completed: true, createdAt: yesterday },
    ],
    attachments: [],
    comments: [],
    activity: [
      { id: 'act-009a', action: 'created task', userId: 'user-john', userName: 'John Smith', createdAt: lastWeek },
      { id: 'act-009b', action: 'marked as completed', userId: 'user-john', userName: 'John Smith', createdAt: yesterday },
    ],
    relatedItems: [],
    createdAt: lastWeek,
    updatedAt: yesterday,
    completedAt: yesterday,
  },
  {
    id: 'task-010',
    organizationId: 'org-codin',
    creatorId: 'user-george',
    assigneeId: 'user-george',
    title: 'Review fleet data analytics',
    description: 'Analyze fleet utilization data and prepare insights for the quarterly business review presentation.',
    status: 'backlog',
    priority: 'low',
    dueDate: nextMonth,
    dueTime: null,
    reminder: 'none',
    recurrence: 'none',
    labels: [mockLabels[6], mockLabels[3]],
    subtasks: [],
    attachments: [],
    comments: [],
    activity: [
      { id: 'act-010a', action: 'created task', userId: 'user-george', userName: 'George Wilson', createdAt: lastWeek },
    ],
    relatedItems: [],
    createdAt: lastWeek,
    updatedAt: lastWeek,
    completedAt: null,
  },
  {
    id: 'task-011',
    organizationId: 'org-codin',
    creatorId: 'user-kelvin',
    assigneeId: 'user-john',
    title: 'Onboard new team member',
    description: 'Prepare onboarding materials and schedule orientation sessions for the new sales associate starting next week.',
    status: 'todo',
    priority: 'medium',
    dueDate: nextWeek,
    dueTime: '09:00',
    reminder: '1_day',
    recurrence: 'none',
    labels: [mockLabels[3], mockLabels[5]],
    subtasks: [
      { id: 'sub-011a', title: 'Prepare employee handbook', completed: true, createdAt: yesterday },
      { id: 'sub-011b', title: 'Set up email and system access', completed: false, createdAt: yesterday },
      { id: 'sub-011c', title: 'Schedule team introductions', completed: false, createdAt: yesterday },
      { id: 'sub-011d', title: 'Assign buddy mentor', completed: false, createdAt: yesterday },
    ],
    attachments: [
      { id: 'att-011', name: 'Onboarding-Checklist.pdf', size: 320000, type: 'application/pdf', url: '#' },
    ],
    comments: [],
    activity: [
      { id: 'act-011a', action: 'created task', userId: 'user-kelvin', userName: 'Kelvin Kijazi', createdAt: yesterday },
    ],
    relatedItems: [],
    createdAt: yesterday,
    updatedAt: yesterday,
    completedAt: null,
  },
  {
    id: 'task-012',
    organizationId: 'org-codin',
    creatorId: 'user-kelvin',
    assigneeId: 'user-kelvin',
    title: 'Update sales deck',
    description: 'Refresh the main sales presentation with updated case studies, pricing, and product screenshots.',
    status: 'completed',
    priority: 'medium',
    dueDate: twoDaysAgo,
    dueTime: null,
    reminder: 'none',
    recurrence: 'none',
    labels: [mockLabels[0], mockLabels[7]],
    subtasks: [
      { id: 'sub-012a', title: 'Update pricing slides', completed: true, createdAt: lastWeek },
      { id: 'sub-012b', title: 'Add new case study', completed: true, createdAt: lastWeek },
      { id: 'sub-012c', title: 'Refresh product screenshots', completed: true, createdAt: twoDaysAgo },
    ],
    attachments: [
      { id: 'att-012', name: 'Sales-Deck-2026.pptx', size: 8400000, type: 'application/vnd.openxmlformats-officedocument.presentationml.presentation', url: '#' },
    ],
    comments: [
      { id: 'com-012', authorId: 'user-john', authorName: 'John Smith', text: 'Looks great! The new case study really strengthens our value proposition.', createdAt: twoDaysAgo },
    ],
    activity: [
      { id: 'act-012a', action: 'created task', userId: 'user-kelvin', userName: 'Kelvin Kijazi', createdAt: lastWeek },
      { id: 'act-012b', action: 'marked as completed', userId: 'user-kelvin', userName: 'Kelvin Kijazi', createdAt: twoDaysAgo },
    ],
    relatedItems: [],
    createdAt: lastWeek,
    updatedAt: twoDaysAgo,
    completedAt: twoDaysAgo,
  },
];
