import {
  CalendarColor,
  CalendarEvent,
  CalendarItem,
  ExternalCalendarSync,
  Participant,
} from './types';

export const CALENDAR_COLORS: CalendarColor[] = [
  { id: 'red', name: 'Crimson', bg: '#fdf2f2', border: '#f87171', text: '#991b1b', dot: '#dc2626' },
  { id: 'blue', name: 'Ocean Blue', bg: '#eff6ff', border: '#60a5fa', text: '#1e40af', dot: '#2563eb' },
  { id: 'emerald', name: 'Emerald Green', bg: '#ecfdf5', border: '#34d399', text: '#065f46', dot: '#059669' },
  { id: 'amber', name: 'Amber Gold', bg: '#fffbeb', border: '#fbbf24', text: '#92400e', dot: '#d97706' },
  { id: 'purple', name: 'Royal Purple', bg: '#faf5ff', border: '#c084fc', text: '#6b21a8', dot: '#9333ea' },
  { id: 'indigo', name: 'Deep Indigo', bg: '#eef2ff', border: '#818cf8', text: '#3730a3', dot: '#4f46e5' },
  { id: 'teal', name: 'Nordic Teal', bg: '#f0fdfa', border: '#2dd4bf', text: '#115e59', dot: '#0d9488' },
  { id: 'slate', name: 'Graphite Slate', bg: '#f8fafc', border: '#94a3b8', text: '#334155', dot: '#64748b' },
];

export const MOCK_PARTICIPANTS: Participant[] = [
  {
    id: 'user-self',
    name: 'Alex Morgan (You)',
    email: 'alex.morgan@codin.io',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=80',
    role: 'organizer',
    status: 'accepted',
    jobTitle: 'VP of Product',
    department: 'Product',
  },
  {
    id: 'user-maya',
    name: 'Maya Chen',
    email: 'maya.chen@codin.io',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=80',
    role: 'required',
    status: 'accepted',
    jobTitle: 'Principal Designer',
    department: 'Design',
  },
  {
    id: 'user-lee',
    name: 'Lee Robinson',
    email: 'lee@codin.io',
    avatar: 'https://github.com/leerob.png',
    role: 'required',
    status: 'accepted',
    jobTitle: 'VP of Product Engineering',
    department: 'Engineering',
  },
  {
    id: 'user-guillermo',
    name: 'Guillermo Rauch',
    email: 'rauchg@codin.io',
    avatar: 'https://github.com/rauchg.png',
    role: 'optional',
    status: 'tentative',
    jobTitle: 'Chief Executive Officer',
    department: 'Executive',
  },
  {
    id: 'user-delba',
    name: 'Delba de Oliveira',
    email: 'delba.oliveira@codin.io',
    avatar: 'https://github.com/delbaoliveira.png',
    role: 'required',
    status: 'accepted',
    jobTitle: 'Staff DX Engineer',
    department: 'Developer Experience',
  },
  {
    id: 'user-tim',
    name: 'Tim Neutkens',
    email: 'tim@codin.io',
    avatar: 'https://github.com/timneutkens.png',
    role: 'required',
    status: 'declined',
    jobTitle: 'Framework Architect',
    department: 'Core Framework',
  },
  {
    id: 'user-sarah',
    name: 'Sarah Jenkins',
    email: 'sarah.j@acmecorp.com',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=80',
    role: 'required',
    status: 'pending',
    jobTitle: 'Enterprise Procurement Lead',
    department: 'Acme Corp',
  },
];

export const INITIAL_CALENDARS: CalendarItem[] = [
  {
    id: 'cal-work',
    name: 'Work',
    color: CALENDAR_COLORS[0], // Crimson
    category: 'personal',
    description: 'Primary work meetings, 1:1s, and design syncs',
    isVisible: true,
    isDefault: true,
    ownerName: 'Alex Morgan',
    ownerEmail: 'alex.morgan@codin.io',
  },
  {
    id: 'cal-personal',
    name: 'Personal',
    color: CALENDAR_COLORS[1], // Blue
    category: 'personal',
    description: 'Personal appointments, health, and family schedules',
    isVisible: true,
    ownerName: 'Alex Morgan',
    ownerEmail: 'alex.morgan@personal.com',
  },
  {
    id: 'cal-team',
    name: 'Team Calendar',
    color: CALENDAR_COLORS[2], // Emerald
    category: 'shared',
    description: 'Product & Engineering sprint ceremonies and releases',
    isVisible: true,
    ownerName: 'Codin Product Org',
    ownerEmail: 'product-team@codin.io',
    sharedWithCount: 18,
  },
  {
    id: 'cal-operations',
    name: 'Operations & Exec',
    color: CALENDAR_COLORS[3], // Amber
    category: 'shared',
    description: 'Quarterly reviews, board meetings, and hiring syncs',
    isVisible: true,
    ownerName: 'Operations Team',
    ownerEmail: 'ops@codin.io',
    sharedWithCount: 8,
  },
  {
    id: 'cal-google-sync',
    name: 'Google Calendar (Sync)',
    color: CALENDAR_COLORS[5], // Indigo
    category: 'external',
    description: 'Synced with alex.m@gmail.com',
    isVisible: true,
    ownerName: 'Alex Morgan',
    ownerEmail: 'alex.m@gmail.com',
    syncSource: 'google',
    lastSyncedAt: '5 minutes ago',
  },
  {
    id: 'cal-holidays',
    name: 'Holidays & Observances',
    color: CALENDAR_COLORS[7], // Slate
    category: 'other',
    description: 'Official corporate and public holidays',
    isVisible: true,
    isReadOnly: true,
    ownerName: 'People & Culture',
    ownerEmail: 'hr@codin.io',
  },
];

export const INITIAL_EXTERNAL_SYNCS: ExternalCalendarSync[] = [
  {
    id: 'sync-google-1',
    provider: 'google',
    email: 'alex.m@gmail.com',
    name: 'Google Workspace',
    status: 'connected',
    lastSynced: 'Just now',
    autoSyncIntervalMinutes: 15,
    selectedCalendars: ['Work Schedule', 'Consulting & Advising'],
  },
  {
    id: 'sync-outlook-1',
    provider: 'outlook',
    email: 'alex.morgan@partner.microsoft.com',
    name: 'Microsoft 365 Exchange',
    status: 'disconnected',
    lastSynced: '2 days ago',
    autoSyncIntervalMinutes: 30,
    selectedCalendars: [],
  },
  {
    id: 'sync-apple-1',
    provider: 'apple',
    email: 'alex.morgan@icloud.com',
    name: 'iCloud Calendar',
    status: 'disconnected',
    lastSynced: 'Never',
    autoSyncIntervalMinutes: 60,
    selectedCalendars: [],
  },
];

// Helper to construct dynamic dates relative to current viewing month (August 2026 or today)
export function generateInitialEvents(): CalendarEvent[] {
  return [
    {
      id: 'evt-1',
      calendarId: 'cal-work',
      title: 'Weekly Operations & Metric Sync',
      description: 'Reviewing quarterly retention, active workspace seats, and infrastructure runway ahead of the Q3 board meeting.',
      location: 'Executive Boardroom & Virtual',
      meetingUrl: 'https://meet.codin.io/ops-weekly-778',
      meetingProvider: 'meet',
      startDate: '2026-08-24',
      startTime: '10:00',
      endDate: '2026-08-24',
      endTime: '11:00',
      allDay: false,
      timezone: 'America/New_York (EDT)',
      organizer: MOCK_PARTICIPANTS[0],
      participants: [MOCK_PARTICIPANTS[0], MOCK_PARTICIPANTS[1], MOCK_PARTICIPANTS[2], MOCK_PARTICIPANTS[3]],
      currentUserStatus: 'accepted',
      reminders: [15, 60],
      availability: 'busy',
      visibility: 'public',
      attachments: [
        { id: 'att-1', name: 'Q3_Operations_Deck_v4.pdf', size: '3.8 MB', type: 'PDF' },
        { id: 'att-2', name: 'Infrastructure_Capacity_Model.xlsx', size: '1.2 MB', type: 'Excel' },
      ],
      tasks: [
        { id: 'tsk-1', title: 'Prepare latency benchmarks for Europe cluster', completed: true, dueDate: '2026-08-24' },
        { id: 'tsk-2', title: 'Send pre-read deck to Guillermo and board members', completed: false, dueDate: '2026-08-24' },
      ],
      relatedEmail: {
        id: 'em-101',
        subject: 'Operations Review: Pre-read materials & agenda',
        sender: 'Maya Chen',
        snippet: 'Attached are the updated usage numbers for July and the forecast for August launch.',
        date: 'Aug 23, 4:15 PM',
      },
      relatedChat: {
        channelId: 'ch-ops',
        channelName: '#operations-sync',
        lastMessage: 'Maya: Updated slide 6 with the enterprise contract tiers.',
        unreadCount: 3,
      },
      aiNotes: {
        summary: 'Key focus: Infrastructure margins expanded by 8% MoM. Enterprise churn reduced to 0.4%.',
        agenda: ['10:00 - 10:15: Revenue & Pipeline Review', '10:15 - 10:40: Architecture Scaling for V2', '10:40 - 11:00: Q&A & Action Assignments'],
        actionItems: ['Finalize AWS commit discount by Friday', 'Maya to polish mobile calendar prototypes'],
        preparationTips: ['You have 2 pending tasks before this call', 'Guillermo requested slide 12 clarification via Chat'],
      },
      createdAt: '2026-08-20T10:00:00Z',
      updatedAt: '2026-08-23T16:00:00Z',
    },
    {
      id: 'evt-2',
      calendarId: 'cal-work',
      title: 'Design Critique: Unified Calendar & Workspace Rail',
      description: 'Critique and walkthrough of the new Calendar workspace, month/week views, scheduling assistant, and mobile responsive states.',
      location: 'Design Studio & Figma Live',
      meetingUrl: 'https://meet.codin.io/design-crit-332',
      meetingProvider: 'meet',
      startDate: '2026-08-24',
      startTime: '14:00',
      endDate: '2026-08-24',
      endTime: '15:00',
      allDay: false,
      timezone: 'America/New_York (EDT)',
      organizer: MOCK_PARTICIPANTS[1], // Maya
      participants: [MOCK_PARTICIPANTS[1], MOCK_PARTICIPANTS[0], MOCK_PARTICIPANTS[4], MOCK_PARTICIPANTS[5]],
      currentUserStatus: 'accepted',
      reminders: [10],
      availability: 'busy',
      visibility: 'public',
      attachments: [
        { id: 'att-3', name: 'Calendar_Design_Tokens_Spec.pdf', size: '6.4 MB', type: 'PDF' },
      ],
      tasks: [
        { id: 'tsk-3', title: 'Verify contrast ratios on dark mode calendar grid', completed: false, dueDate: '2026-08-24' },
      ],
      relatedChat: {
        channelId: 'ch-design',
        channelName: '#product-design',
        lastMessage: 'Ari: The mobile prototype is ready for testing.',
      },
      aiNotes: {
        summary: 'Reviewing 5 key interaction models: Quick Event Popover, Multi-Attendee Availability Heatmap, Month Overflow Drawer, and Natural Language Creation.',
        agenda: ['Walkthrough of 1440px desktop grid', 'Scheduling assistant demo', 'Accessibility & high-contrast testing'],
      },
      createdAt: '2026-08-21T11:00:00Z',
      updatedAt: '2026-08-24T08:00:00Z',
    },
    {
      id: 'evt-3',
      calendarId: 'cal-team',
      title: 'Sprint 42 Planning & Roadmap Commit',
      description: 'Bi-weekly sprint planning session for the frontend platform and real-time synchronization engine.',
      location: 'Engineering Hub',
      meetingUrl: 'https://meet.codin.io/eng-sprint-42',
      meetingProvider: 'meet',
      startDate: '2026-08-25',
      startTime: '09:30',
      endDate: '2026-08-25',
      endTime: '11:00',
      allDay: false,
      timezone: 'America/New_York (EDT)',
      recurrence: { frequency: 'biweekly', interval: 2 },
      organizer: MOCK_PARTICIPANTS[2], // Lee
      participants: [MOCK_PARTICIPANTS[2], MOCK_PARTICIPANTS[0], MOCK_PARTICIPANTS[4], MOCK_PARTICIPANTS[5]],
      currentUserStatus: 'accepted',
      reminders: [15],
      availability: 'busy',
      visibility: 'public',
      attachments: [],
      tasks: [
        { id: 'tsk-4', title: 'Triage P1 performance issues for Next.js 15.6 Turbopack', completed: true },
      ],
      createdAt: '2026-08-18T09:00:00Z',
      updatedAt: '2026-08-24T12:00:00Z',
    },
    {
      id: 'evt-4',
      calendarId: 'cal-operations',
      title: 'Enterprise Architecture & Procurement (Acme Corp)',
      description: 'Technical evaluation call with Acme Corp security and IT infrastructure leads regarding SSO, data residency, and SOC2 compliance.',
      location: 'Virtual Conference',
      meetingUrl: 'https://meet.codin.io/acme-procurement-call',
      meetingProvider: 'meet',
      startDate: '2026-08-25',
      startTime: '15:30',
      endDate: '2026-08-25',
      endTime: '16:30',
      allDay: false,
      timezone: 'America/New_York (EDT)',
      organizer: MOCK_PARTICIPANTS[0],
      participants: [MOCK_PARTICIPANTS[0], MOCK_PARTICIPANTS[6], MOCK_PARTICIPANTS[3]],
      currentUserStatus: 'accepted',
      reminders: [30],
      availability: 'busy',
      visibility: 'confidential',
      attachments: [
        { id: 'att-4', name: 'SOC2_Type_II_Executive_Summary.pdf', size: '1.9 MB', type: 'PDF' },
        { id: 'att-5', name: 'Acme_Custom_MSA_Draft.docx', size: '440 KB', type: 'Word' },
      ],
      tasks: [
        { id: 'tsk-5', title: 'Confirm EU data isolation cluster URL', completed: false, dueDate: '2026-08-25' },
      ],
      aiNotes: {
        summary: 'Acme Corp has 4,200 prospective seats. Primary questions relate to SAML SSO, audit log export APIs, and Slack migration.',
        preparationTips: ['Sarah Jenkins requested verification of webhook event delivery guarantees.', 'Guillermo is joining for the first 15 minutes.'],
      },
      createdAt: '2026-08-22T14:00:00Z',
      updatedAt: '2026-08-24T09:30:00Z',
    },
    {
      id: 'evt-5',
      calendarId: 'cal-personal',
      title: 'Doctor Appointment & Health Check',
      description: 'Routine annual checkup with Dr. Henderson.',
      location: 'Downtown Medical Center, Suite 400',
      startDate: '2026-08-26',
      startTime: '08:00',
      endDate: '2026-08-26',
      endTime: '09:15',
      allDay: false,
      timezone: 'America/New_York (EDT)',
      organizer: MOCK_PARTICIPANTS[0],
      participants: [MOCK_PARTICIPANTS[0]],
      currentUserStatus: 'accepted',
      reminders: [60, 1440],
      availability: 'oof',
      visibility: 'private',
      attachments: [],
      tasks: [],
      createdAt: '2026-08-10T10:00:00Z',
      updatedAt: '2026-08-10T10:00:00Z',
    },
    {
      id: 'evt-6',
      calendarId: 'cal-work',
      title: '1:1 Alex & Guillermo',
      description: 'Strategic roadmap sync, hiring plan for Q4, and Next-Gen platform demo review.',
      location: 'CEO Office & Walk in the Park',
      meetingUrl: 'https://meet.codin.io/1on1-alex-guillermo',
      meetingProvider: 'meet',
      startDate: '2026-08-26',
      startTime: '13:00',
      endDate: '2026-08-26',
      endTime: '13:45',
      allDay: false,
      timezone: 'America/New_York (EDT)',
      recurrence: { frequency: 'weekly', interval: 1 },
      organizer: MOCK_PARTICIPANTS[3], // Guillermo
      participants: [MOCK_PARTICIPANTS[3], MOCK_PARTICIPANTS[0]],
      currentUserStatus: 'accepted',
      reminders: [10],
      availability: 'busy',
      visibility: 'public',
      attachments: [],
      tasks: [
        { id: 'tsk-6', title: 'Draft hiring roadmap for AI & Design leads', completed: false, dueDate: '2026-08-26' },
      ],
      aiNotes: {
        summary: 'Follow-up from last week: Guillermo agreed to increase budget for the unified communication suite by 20%.',
        agenda: ['Product launch readiness review', 'Key enterprise customer feedback from NYC summit', 'Engineering staffing targets'],
      },
      createdAt: '2026-08-15T15:00:00Z',
      updatedAt: '2026-08-23T18:00:00Z',
    },
    {
      id: 'evt-7',
      calendarId: 'cal-work',
      title: 'Customer Advisory Board (CAB) Session',
      description: 'Monthly interactive product feedback session with 12 top design and technology leaders.',
      location: 'Auditorium & Live Stream',
      meetingUrl: 'https://meet.codin.io/cab-august-2026',
      meetingProvider: 'meet',
      startDate: '2026-08-27',
      startTime: '11:00',
      endDate: '2026-08-27',
      endTime: '12:30',
      allDay: false,
      timezone: 'America/New_York (EDT)',
      organizer: MOCK_PARTICIPANTS[0],
      participants: [MOCK_PARTICIPANTS[0], MOCK_PARTICIPANTS[1], MOCK_PARTICIPANTS[2], MOCK_PARTICIPANTS[4], MOCK_PARTICIPANTS[6]],
      currentUserStatus: 'accepted',
      reminders: [30],
      availability: 'busy',
      visibility: 'public',
      attachments: [
        { id: 'att-6', name: 'CAB_August_Feedback_Guide.pdf', size: '2.1 MB', type: 'PDF' },
      ],
      tasks: [],
      createdAt: '2026-08-19T10:00:00Z',
      updatedAt: '2026-08-24T11:00:00Z',
    },
    {
      id: 'evt-8',
      calendarId: 'cal-team',
      title: 'Engineering Demo & Ship Celebration',
      description: 'Bi-weekly demo session showcasing what all cross-functional squads shipped across Mail, Chat, Contacts, Tasks, and Calendar.',
      location: 'Main All-Hands Stage',
      meetingUrl: 'https://meet.codin.io/eng-demo-ship',
      meetingProvider: 'meet',
      startDate: '2026-08-28',
      startTime: '16:00',
      endDate: '2026-08-28',
      endTime: '17:00',
      allDay: false,
      timezone: 'America/New_York (EDT)',
      organizer: MOCK_PARTICIPANTS[2],
      participants: [MOCK_PARTICIPANTS[2], MOCK_PARTICIPANTS[0], MOCK_PARTICIPANTS[1], MOCK_PARTICIPANTS[4], MOCK_PARTICIPANTS[5]],
      currentUserStatus: 'accepted',
      reminders: [15],
      availability: 'busy',
      visibility: 'public',
      attachments: [],
      tasks: [],
      createdAt: '2026-08-15T12:00:00Z',
      updatedAt: '2026-08-24T12:00:00Z',
    },
    {
      id: 'evt-9',
      calendarId: 'cal-google-sync',
      title: 'Advisory Sync with Open Source Foundation',
      description: 'Advisory committee review regarding web standards, accessibility guidelines, and open protocols.',
      location: 'Google Meet',
      meetingUrl: 'https://meet.google.com/xyz-abcd-efg',
      meetingProvider: 'meet',
      startDate: '2026-08-27',
      startTime: '15:00',
      endDate: '2026-08-27',
      endTime: '16:00',
      allDay: false,
      timezone: 'America/New_York (EDT)',
      organizer: {
        id: 'user-ext-1',
        name: 'Jordan Rivera',
        email: 'jordan@w3c-advisory.org',
        role: 'organizer',
        status: 'accepted',
      },
      participants: [MOCK_PARTICIPANTS[0]],
      currentUserStatus: 'accepted',
      reminders: [15],
      availability: 'busy',
      visibility: 'public',
      attachments: [],
      tasks: [],
      createdAt: '2026-08-20T08:00:00Z',
      updatedAt: '2026-08-20T08:00:00Z',
    },
    {
      id: 'evt-10',
      calendarId: 'cal-holidays',
      title: 'Company Wellness & Learning Day',
      description: 'Company-wide day dedicated to professional growth, wellness, and self-directed exploration. No internal meetings.',
      startDate: '2026-08-31',
      endDate: '2026-08-31',
      allDay: true,
      timezone: 'America/New_York (EDT)',
      organizer: {
        id: 'hr-lead',
        name: 'People Operations',
        email: 'hr@codin.io',
        role: 'organizer',
        status: 'accepted',
      },
      participants: [MOCK_PARTICIPANTS[0], MOCK_PARTICIPANTS[1], MOCK_PARTICIPANTS[2], MOCK_PARTICIPANTS[3]],
      currentUserStatus: 'accepted',
      reminders: [1440],
      availability: 'free',
      visibility: 'public',
      attachments: [],
      tasks: [],
      createdAt: '2026-08-01T00:00:00Z',
      updatedAt: '2026-08-01T00:00:00Z',
    },
    {
      id: 'evt-11',
      calendarId: 'cal-work',
      title: 'Product Strategy Review: Q4 Goals',
      description: 'High-level roadmap alignment on upcoming mobile releases and AI workflow automations.',
      location: 'Conference Room Alpha',
      meetingUrl: 'https://meet.codin.io/strat-q4',
      meetingProvider: 'meet',
      startDate: '2026-08-19',
      startTime: '11:00',
      endDate: '2026-08-19',
      endTime: '12:30',
      allDay: false,
      timezone: 'America/New_York (EDT)',
      organizer: MOCK_PARTICIPANTS[0],
      participants: [MOCK_PARTICIPANTS[0], MOCK_PARTICIPANTS[1], MOCK_PARTICIPANTS[3]],
      currentUserStatus: 'accepted',
      reminders: [15],
      availability: 'busy',
      visibility: 'public',
      attachments: [],
      tasks: [],
      createdAt: '2026-08-10T10:00:00Z',
      updatedAt: '2026-08-19T10:00:00Z',
    },
    {
      id: 'evt-12',
      calendarId: 'cal-work',
      title: 'AI Scheduling Engine Architecture',
      description: 'Technical deep-dive on natural language parser, constraint solver, and multi-tenant availability caching.',
      location: 'Engineering Lab 2',
      meetingUrl: 'https://meet.codin.io/ai-sched-arch',
      meetingProvider: 'meet',
      startDate: '2026-08-12',
      startTime: '14:00',
      endDate: '2026-08-12',
      endTime: '15:30',
      allDay: false,
      timezone: 'America/New_York (EDT)',
      organizer: MOCK_PARTICIPANTS[4],
      participants: [MOCK_PARTICIPANTS[4], MOCK_PARTICIPANTS[0], MOCK_PARTICIPANTS[2]],
      currentUserStatus: 'accepted',
      reminders: [10],
      availability: 'busy',
      visibility: 'public',
      attachments: [],
      tasks: [],
      createdAt: '2026-08-05T09:00:00Z',
      updatedAt: '2026-08-12T14:00:00Z',
    },
  ];
}
